#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys, math

if len(sys.argv) == 8:
	try:
		x0, y0, z0 = float(sys.argv[1]), float(sys.argv[2]), float(sys.argv[3])
		x1, y1, z1 = float(sys.argv[4]), float(sys.argv[5]), float(sys.argv[6])
		n = int(sys.argv[7])
	except:
		print "Please enter only numbers"
		sys.exit(84)
	if n >= 0:
		vx = x1 - x0
		vy = y1 - y0
		vz = z1 - z0
		tnx = n * vx + x1
		tny = n * vy + y1
		tnz = n * vz + z1
		print "The speed vector coordinates are :"
		print "(%.2f;%.2f;%.2f)" % (vx, vy, vz)
		print "At time t+%d, ball coordinates will be :" % (n)
		print "(%.2f;%.2f;%.2f)" % (tnx, tny, tnz)
		if (z1 > 0.0 and float(tnz) < 0.0) or (z1 < 0.0 and float(tnz) > 0.0):
			Vz0 = math.sqrt((vx * vx) + (vy * vy))
			angle = 90 - math.degrees(math.atan2(Vz0, vz))
			if angle < 0:
				angle = -angle
			print "The incidence angle is :"	
			print "%.2f degrees" % angle
		else:
			print "The ball won't reach the bat."
	else:
		print "N must be greater or equal to 0"
		sys.exit(84)
else:
	print "Error: please enter at least 7 arguments"
	sys.exit(84)
